name: MoME
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py310h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - ipykernel=6.29.5=pyh3099207_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.0.16=h5eee18b_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=26.2.0=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h993c535_1
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.0=pyhe01879c_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.7.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - alembic==1.16.4
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - axial-positional-embedding==0.3.12
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.2.1
      - colorlog==6.9.0
      - colt5-attention==0.11.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.6.0
      - deprecate-kwargs==0.1.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - filelock==3.18.0
      - fonttools==4.58.5
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.2.3
      - hf-xet==1.1.5
      - huggingface-hub==0.32.2
      - hyper-connections==0.2.1
      - idna==3.10
      - ipython==8.36.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - local-attention==1.11.1
      - mako==1.3.10
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - modelscope==1.28.1
      - mpmath==1.3.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - networkx==3.4.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - optuna==3.6.2
      - pandas==2.2.3
      - peft==0.15.2
      - pillow==11.3.0
      - product-key-memory==0.2.11
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==20.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - pytz==2025.2
      - pyyaml==6.0.2
      - reformer-pytorch==1.4.4
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentry-sdk==2.32.0
      - setproctitle==1.3.6
      - smmap==5.0.2
      - sqlalchemy==2.0.41
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchinfo==1.8.0
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.52.3
      - triton==3.1.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.19.11
      - xxhash==3.5.0
      - yarl==1.20.1
